-- liquibase formatted sql

-- changeset sergey:1
create table images
(
    id         integer generated by default as identity
        primary key,
    name_image varchar(255)
);

alter table images
    owner to shopuser;

create table users
(
    id         integer generated by default as identity
        primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    role       varchar(255),
    image_id   integer
        constraint fk17herqt2to4hyl5q5r5ogbxk9
            references images
);

alter table users
    owner to shopuser;

create table ads
(
    id          integer generated by default as identity
        primary key,
    description text,
    price       integer not null,
    title       text,
    image_id    integer
        constraint fkpof1jpi73grtcoehm9u9vunye
            references images,
    user_id     integer
        constraint fkhjy5cj20i6dn8t38as5poqt7b
            references users
            on delete cascade
);

alter table ads
    owner to shopuser;

create table comments
(
    id         integer generated by default as identity
        primary key,
    created_at timestamp,
    text       text,
    ad_id      integer
        constraint fk8c6328vy3jubusjo17ucraqf1
            references ads
            on delete cascade,
    user_id    integer
        constraint fk8omq0tc18jd43bu5tjh6jvraq
            references users
);

alter table comments
    owner to shopuser;
CREATE INDEX username ON users(email)